{
  "dlStore": {
    "nameApp": "DL Store",
    "versionNameNew": "16.0.4",
    "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/app/DLStore_v16.0.3.apk",
    "manufacturer": "sony,xiaomi,oneplus",
    "checkDate": "3",
    "linkBecause": "Một số thành phần vì lợi ích cá nhân bán sản phẩm mod.\nLên mạng lại nói : 2026 rồi vẫn dùng DL ak  \uD83E\uDD29\n Vui lòng mai vào lại là được !",
    "note": "\uD83D\uDD14\uD83D\uDD14\uD83D\uDD14 Thông báo \uD83D\uDD14\uD83D\uDD14\uD83D\uDD14 \n\nĐể tuân thủ chính pháp luật Việt Nam các ứng dụng xem thể thao, phim truyện không được phép đã đang dừng hoạt động.\nMọi người nên tìm đến các ứng dụng chính thống như VTV Go, FPTPlay, MyTV, TV360, Galaxy và một số ứng dụng khác.",
    "ad": "",
    "linkWeb": "https://sites.google.com/view/dinhlaptv"
  },
  "homeTV": {
    "versionHomeTVShop": "VuaXiaomi,16-GoldMiHungYen,18-shop,16-shop,19-shop,HomeTVShop,TiviXiaomiHaiPhong,DienMayChoTong,dienmaymi.vn,15.0.5-Long Bien,16-TongKhoXiaomi,XiaomiPhuTho,XiaomiStoreHaNoi,18-Lap,Mi3s,ShopMi3s,tivixiaomi.com,XiaomiVietTri,NgocNguyen,MigiasiMienNam,TVXiaomiBinhDuong,16-XiaomiBinhDinh,16-TiviXiaomiNinhBinh,VuaRobot,DienMayHalo,18-INNOVAC-GROUP,18-DienMayCongTrinh,18-DienMayHalo,16-XiaomiVietNam,18-TiviXiaomiVietNam,TiviXiaomiVietNam,15-Halo,15-DienMayXiaomi,16-LongTV,14.0.5-XiaomiHanoi,16-Mi3S,13.0.1,1616161616,15.0.4,15.0.2,16.0.1,16.0.0,16.0.2,6.0,10.0.0,8.0.1,13.0.0,13.0.2,9.0.2",
    "timeShop":"20260418",
    "linkHomeTVShop": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/app/Home_TV_vHomeTVShopV2_v23_1900000000_MoDinhLap_Chiase.apk",
    "versionHomeTVLap": "18-Lap,9.0.2,19,20,21,22,19-Lap,19-DinhLap,18,18-DinhLap,16-XiaomiBinhDinh,16,15,14,13,12,10,9,8,16.0.2,16-MiThaiNguyen,15-DienMayXiaomi",
    "timeLap":"20250426",
    "linkHomeTVLap": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/app/Home_TV_vHomeTVDinhLap_v23_1900000000_MoDinhLap_Chiase.apk",
    "packageFake": "com.xiaomi.haki,com.xiaomi.hometv,com.xiaomi.mitv.voicecontrol,com.dinhlap.mitv.voicecontrol",
    "linkHomeTVMod": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/app/HomeTV_vM.apk"
  },
  "apps": [
    {
      "name": "VTVGo TV",
      "versionNameNew": "12.5.28",
      "categoty": "Truyền hình trực tuyến",
      "rated": "4",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVGoTV/Vtv_go_banner.png",
      "packageName": "vn.vtv.vtvgotv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVGoTV/VTVgoTV_v12.5.28_DL.apk",
      "note": "VTVgo là hệ thống xem truyền hình trực tuyến chính thức của Đài Truyền hình Việt Nam cho phép khán giả VTV xem trực tiếp, xem lại, xem theo chủ đề mọi chương trình truyền hình cũng như thưởng thức kho video độc quyền lớn nhất Việt Nam trên nhiều lĩnh vực.\nCác tính năng chính:\n1. Kênh TV\n• Xem trực tuyến các kênh truyền hình Việt Nam: VTV1, VTV2, VTV3, VTV4, VTV5, VTV6, VTV7, VTV8, VTV9, VTV5 Tây Nguyên và VTV5 Tây Nam Bộ.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVGoTV/anh.png"
    },
    {
      "name": "Youtube TV",
      "versionNameNew": "2.02.08",
      "categoty": "Giải trí",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/youtube_tv.png",
      "packageName": "com.google.android.youtube.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/YoutubeTV_v2.02.08.apk",
      "note": "Ứng dụng YoutubeTV bản chính thức của google có quảng cáo .\nCác tính năng phát hành hiện tại:\nChạy trên Android 5 trở lên\nDuyệt qua Tin tức, Trò chơi, Âm nhạc\nDuyệt qua đăng ký, lịch sử, danh sách phát\nPhát video\nThích, Không thích hoặc Đăng ký cho video\nTìm kiếm video\nXem nội dung kênh đã đăng ký\nThay đổi các cài đặt khác nhau cho trình phát video\nXem trước hoạt ảnh cho video\nCác kênh Android TV và hỗ trợ tìm kiếm\"",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh.webp,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh1.jpg"
    },
    {
      "name": "NhacCuaTui",
      "versionNameNew": "5.4.1",
      "categoty": "Âm nhạc",
      "rated": "4",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/NhacCuaTui/NhacCuaTuiTV.jpg",
      "packageName": "vn.nhaccuatui.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/NhacCuaTui/NhacCuaTui-TV_5.4.1.apk",
      "note": "Tổng quan: NhacCuaTui TV là ứng dụng nghe nhạc và xem video trực tuyến hoàn toàn miễn phí trên TV. Với hàng triệu bài hát, video chọn lọc được cập nhật liên tục, giúp bạn dễ dàng tìm kiếm những bài hát mà mình yêu thích. Thỏa sức lưu trữ kho nhạc riêng không giới hạn, hơn thế nữa bạn có thể tận hưởng âm nhạc mọi lúc mọi nơi với tài khoản nghe nhạc được đồng bộ trên điện thoại, TV và Web.Mọi ý kiến, đóng góp cho ứng dụng, các bạn có thể liên lạc địa chỉ email support@nct.vn, rất mong nhận được nhiều phản hồi của các bạn để ứng dụng NhacCuaTui ngày một tốt hơn.Để biết thêm thông tin về Bảo mật và Điều khoản sử dụng NhacCuaTui, vui lòng truy cập:\nhttp://stc.nct.nixcdn.com/static_v8/generals/Chinh_sach_quyen_SHTT.zip\nhttp://www.nhaccuatui.com/thoa_thuan_su_dung.html",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/NhacCuaTui/anh.webp"
    },
    {
      "name": "Bilibili TV",
      "versionNameNew": "1.7.1",
      "rated": "4",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BilibiliTV/logo.png",
      "packageName": "com.bstar.intl.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BilibiliTV/bilibili_modvip_v1.7.1.apk",
      "note": "Cộng đồng video Danmaku, hoạt hình giải trí hai chiều",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BilibiliTV/anh.jpg"
    },
    {
      "name": "⚽ SportsTV",
      "versionNameNew": "5.2.3",
      "categoty": "Thể thao",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SportsTV/ic_SportsTV.png",
      "packageName": "com.sports.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SportsTV/SportsTV_5.2.3.apk",
      "note": "Sport TV là ứng dụng xem truyền hình, bóng đá trực tuyến miễn phí trên Android TV Box\nĐể sử dụng được hãy thêm nguồn vào nhé\nLuôn mới nhất tại đây: bom.so/sportstv",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SportsTV/anh.jpg"
    },
    {
      "name": "Cốc cốc TV Lite",
      "versionNameNew": "1.6",
      "categoty": "Trình duyệt web",
      "rated": "4",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/tv_CocCoc_lite.png",
      "packageName": "com.coccoc.trinhduyet_tvlite",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/CocCocTVLite_1.6.apk",
      "note": "Trình duyệt cốc cốc cho androidTV",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/anh.png,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/tv_CocCoc_lite.png"
    },
    {
      "name": "Cốc cốc TV Bản Nặng",
      "versionNameNew": "127.4.160",
      "categoty": "Trình duyệt web",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/tv_CocCoc_lite.png",
      "packageName": "com.coccoc.trinhduyet_tv",
      "linkDownload": "https://files.coccoc.com/browser/tv/prod/arm/121.4.6167.160/coc_coc_tv_prod_121.4.6167.160_816716020_7plus.apk",
      "note": "Trình duyệt cốc cốc cho androidTV",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/anh.png,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CocCoc/tv_CocCoc_lite.png"
    },
    {
      "name": "Ezviz TV",
      "versionNameNew": "1.1.1.0408",
      "categoty": "Camera",
      "rated": "4",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/EZVIZTV/Ezviz_TV.png",
      "packageName": "com.ezviz.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/EZVIZTV/EzvizTV_1.1.1.0408.apk",
      "note": "Các tính năng chính:\n- Xem luồng trực tiếp độ nét cao từ mọi nơi, Nhìn trong bóng tối với đèn hồng ngoại bật, Phát lại các video đã quay bằng CloudPlay hoặc thẻ SD, Nói chuyện qua âm thanh hai chiều, Nhận cảnh báo tức thì khi phát hiện chuyển động\n- Tùy chỉnh vùng phát hiện và độ nhạy, Đặt lịch để ghi lại những khoảnh khắc quan trọng, Chia sẻ thiết bị với bạn bè và gia đình",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/EZVIZTV/anh.webp"
    },
    {
      "name": "Weather Live°",
      "versionNameNew": "6.20.3",
      "categoty": "Thời tiết",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeatherLive/WeatherLive.png",
      "packageName": "com.apalon.weatherlive",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeatherLive/Weather_Live_pro.apk",
      "note": "Thời tiết đôi khi rất khó dự đoán. Ứng dụng thời tiết chính xác này cho phép tìm hiểu dự báo thời tiết chi tiết trong 14 ngày (7 trong phiên bản miễn phí) mọi lúc mọi nơi, vào bất kỳ thời điểm nào trong ngày hoặc cho những ngày tiếp theo chỉ bằng cách nhấn vào các biểu tượng:\n- Nhiệt độ hiện tại và 'Cảm thấy thích' - Trình theo dõi tia chớp Tốc độ và hướng gió- Thông tin thời tiết về áp suất và lượng mưa- Thời gian bình minh / hoàng hôn\n- Radar thời tiết & bản đồ mưa\n- Tầm nhìn (điều kiện thời tiết để lái xe)\n- Cảnh báo thời tiết & thông báo tình trạng hiện tại\nvà dữ liệu thời tiết hữu ích khác kèm theo hình ảnh động và đồ họa trực tiếp.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeatherLive/anh.png"
    },
    {
      "name": "KCMS",
      "versionNameNew": "1.0.89",
      "categoty": "Karaoke",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KCMS/logo.png",
      "packageName": "com.example.karaokeonline",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KCMS/kcms_1.0.89_44.apk",
      "note": "KCMS nổi lên như một phần mềm karaoke chuyên nghiệp được đánh giá cao. Với giao diện thân thiện, dễ sử dụng và khả năng tương thích với nhiều thiết bị, KCMS không chỉ mang đến trải nghiệm karaoke đỉnh cao mà còn nâng tầm cuộc vui của bạn.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KCMS/anh.png"
    },
    {
      "name": "X-plore",
      "versionNameNew": "4.45.03",
      "categoty": "Tiện ích",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/X-plore/XploreFileManager.png",
      "packageName": "com.lonelycatgames.Xplore",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/X-plore/X-plore_4.45.03_ApkDone.apk",
      "note": "Hướng dẫn sử dụng: www.lonelycatgames.com/docs/xplore Điểm nổi bật: Chế độ xem dạng cây hai ngăn- Root, FTP, SMB1 / SMB2, Sqlite, Zip, Rar, 7zip, DLNA / UPnP explorer, Bản đồ đĩa - xem tệp nào chiếm nhiều dung lượng nhất trên đĩa của bạn - http://bit.ly/xp-disk-map\n- Quyền truy cập bộ nhớ đám mây: Google Drive, OneDrive, Mega.co, Dropbox, Yandex.disk, ОБЛАКО.mail.ru, Webdav và những người khác\n- Truyền tệp SSH (SFTP) và SSH Shell - http://bit.ly/xp-sftp - Máy nghe nhạc,Trình quản lý ứng dụng,USB OTG, Trình xem PDF - Chia sẻ tệp WiFi *** - http://bit.ly/xp-wifi-share - Quản lý tệp từ trình duyệt web trên PC *** - http://bit.ly/xp-wifi-web - Thư mục yêu thích - Trình xem tích hợp cho hình ảnh, âm thanh, văn bản - Trình phát video có phụ đề - Đổi tên hàng loạt- Trình xem hex",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/X-plore/anh.jpg,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/X-plore/anh.webp"
    },
    {
      "name": "LeanKey Keyboard Pro",
      "versionNameNew": "22.06.07_vi-dinhlap",
      "categoty": "Bàn phím",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/LeanKeyKeyboard/LeanKeyKeyboard.png",
      "packageName": "com.liskovsoft.leankeyboard",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/LeanKeyKeyboard/LeanKeyKeyboardPro_v22.06.07_vi.apk",
      "note": "Một số lượng lớn các hộp giải mã tín hiệu thiếu bàn phím tốt. Ứng dụng này nhằm khắc phục sự cố như vậy. Đặc trưng: Hỗ trợ kiểu gõ tiếng việt\n- Hỗ trợ điều khiển từ xa đơn giản\n- Có bố cục cho hầu hết mọi ngôn ngữ\n- Hỗ trợ phím tắt bổ sung (ví dụ: menu)\n** Mã nguồn: https://github.com/yuliskov/LeanKeyKeyboard*\nBàn phím đã được thử nghiệm trên Xiaomi Mi Box, Amazon Fire TV, LETV Smart TV, Nexus Player và các thiết bị khác.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/LeanKeyKeyboard/anh.jpg"
    },
    {
      "name": "VTVPrime",
      "versionNameNew": "1.11.0",
      "categoty": "Truyền hình trực tuyến",
      "rated": "4",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVPrime/banner.png",
      "packageName": "vn.vtvcab.vtvprime.atv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVPrime/VTVprime_v1.11.0.apk",
      "note": "VTVgo là hệ thống xem truyền hình trực tuyến chính thức của Đài Truyền hình Việt Nam cho phép khán giả VTV xem trực tiếp, xem lại, xem theo chủ đề mọi chương trình truyền hình cũng như thưởng thức kho video độc quyền lớn nhất Việt Nam trên nhiều lĩnh vực.\nCác tính năng chính:\n1. Kênh TV\n• Xem trực tuyến các kênh truyền hình Việt Nam: VTV1, VTV2, VTV3, VTV4, VTV5, VTV6, VTV7, VTV8, VTV9, VTV5 Tây Nguyên và VTV5 Tây Nam Bộ.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVPrime/anh1.png,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVPrime/anh2.png"
    },
    {
      "name": "FPT Play",
      "versionNameNew": "7.27.1",
      "categoty": "Truyền hình trực tuyến",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/FPTPlay/banner_fptplay.jpg",
      "packageName": "net.fptplay.ottbox",
      "linkDownload": "https://github.com/DinhLap96/ListTivi/releases/download/AppTV/FPTPlay_v7.27.1-DL.apk",
      "note": "Nếu cài lỗi thì gỡ ra trước rồi cài lại.\nỨng dụng FPT Play for Android TV đa nền tảng với hàng trăm kênh truyền hình Việt Nam và quốc tế, hàng nghìn giờ phim truyện và show giải trí hấp dẫn. Giao diện hiện đại, thân thiện, tốc độ nhanh, ổn định, chất lượng chuẩn HD trên mọi nền tảng, FPT Play mang đến cho người dùng trải nghiệm giải trí trọn vẹn mọi lúc, mọi nơi.\nPhát sóng trực tiếp các giải thể thao hàng đầu thế giới như Ngoại hạng Anh, Seria A, cúp C1 (trên nhóm kênh K+), AFF, AFC…\nHotline: 19006600\nWebsite: https://fptplay.vn/\nFanpage: https://www.facebook.com/fptplay",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/FPTPlay/anh.png,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/FPTPlay/anh1.png"
    },
    {
      "name": "QuanTV",
      "versionNameNew": "250921",
      "categoty": "Truyền hình trực tuyến",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/QuanTV/logo.png",
      "packageName": "vn.quan.quantv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/QuanTV/QuanTV_v250921.apk",
      "note": "Xem truyền hình, mượt",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/QuanTV/anh.png"
    },
    {
      "name": "HTVC Android TV",
      "versionNameNew": "1.1.1",
      "categoty": "Truyền hình trực tuyến",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/HTVC/logo.png",
      "packageName": "vn.com.tms.sonyflix",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/HTVC/HTVC_AndroiTV_1.1.1.apk",
      "note": "HTVC - Ứng dụng xem Truyền hình trực tuyến mọi lúc mọi nơi\n• Thưởng thức trực tuyến hơn 90 kênh truyền hình trong và ngoài nước với chất lượng HD (LiveTV)\n• Thỏa thích trải nghiệm gói kênh HTV và HTVC với hàng loạt nội dung đặc sắc\n• Tương tác cùng kho Video khổng lồ với hơn 10.000 chương trình giải trí hấp dẫn, phong phú về thể loại và được cập nhật mới liên tục\n• Chất lượng hình ảnh ổn định, sắc nét trên nền âm thanh sống động.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/HTVC/anh.png"
    },
    {
      "name": "TV360",
      "versionNameNew": "4.4",
      "categoty": "Truyền hình trực tuyến",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TV360/TV360.png",
      "packageName": "com.viettel.tv360.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TV360/TV360-AndroidTV_4.4_DL.apk",
      "note": "Tất cả đều có trên ứng dụng TV360: Gần 200 kênh truyền hình VTV, HTV, VTVCab, VTC, kênh nước ngoài như Fox Movies, Box Movies, Hollywood … và các đài địa phương. Trực tiếp bóng đá Europa League, SeaGame, AFF Suzuki Cup, V – League, Cúp Quốc Gia, LaLiga, Bundesliga và nhiều giải đấu khác.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TV360/anh.jpg"
    },
    {
      "name": "MyTV",
      "versionNameNew": "4.67.0_530_20251008",
      "categoty": "Truyền hình trực tuyến",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MyTV/MyTV.png",
      "packageName": "vn.mytvnet.b2cott",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MyTV/MyTV_v4.67.0_530_20251008.apk",
      "note": "Mod chặn quaảng cáo, không hiện logo mytv\nTHOẢ SỨC THƯ GIÃN – MÃN NHÃN TRẢI NGHIỆM CÙNG ỨNG DỤNG MyTV\n- Xem cả ngày không chán gần 200 kênh truyền hình đặc sắc trong nước và quốc tế.\n- Kho phim dài tập chiếu song song luôn được cập nhật liên tục của Trung Quốc, Hàn Quốc, Thái Lan…\n- Series phim chiếu rạp mới và hoành tráng nhất update từng ngày.\n- Ăn - ngủ cùng các giải đấu thể thao đỉnh cao trên thế giới.\nChi tiết liên hệ: 18001166; website: www.mytv.com.vn",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MyTV/anh.webp"
    },
    {
      "name": "SCTVOnline",
      "versionNameNew": "5.26.20.92280",
      "categoty": "Truyền hình trực tuyến",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SCTV/anh.jpg",
      "packageName": "io.vimai.sctvonline.androidtv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SCTV/SCTVOnline_v5.26.20.92280.apk",
      "note": "SCTVOnline là ứng dụng giải trí đa nền tảng hiện đại, với nội dung phong phú, đa dạng và luôn được cập nhật nhanh chóng. Ứng dụng cung cấp cho khán giả nguồn chương trình giải trí đỉnh cao, với các nội dung nổi bật như:\n- Gần 80 kênh truyền hình chuẩn HD: đa dạng tiêu chí, phong phú thể loại nội dung.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SCTV/anh.png"
    },
    {
      "name": "iMedia - Xem Tivi HD",
      "versionNameNew": "25.04.06.B",
      "categoty": "Truyền hình trực tuyến",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/iMedia/iMedia.png",
      "packageName": "com.kt.apps.media.xemtv.beta",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/iMedia/iMedia-25.04.06.B_mod.apk",
      "note": "Ứng dụng iMedia là một ứng dụng miễn phí trên nền tảng Android TV, cho phép người dùng xem truyền hình và phát thanh phổ thông mà không cần phải trả bất kỳ khoản phí nào. Ứng dụng cũng không có quảng cáo, mang lại cho người dùng một trải nghiệm sử dụng không bị gián đoạn.iMedia có giao diện đơn giản và dễ sử dụng, với các tính năng như chọn kênh truyền hình hoặc phát thanh yêu thích của bạn, tìm kiếm nhanh chóng",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/iMedia/anh.jpg"
    },
    {
      "name": "VTVcab ON",
      "versionNameNew": "2.2.1",
      "rated": "3",
      "categoty": "Truyền hình trực tuyến",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/VTVCab_ON.png",
      "packageName": "com.vtvcab.onTV",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/VTVcab-ON-AndroidTV_2.2.1.apk",
      "note": "VTVcab trân trọng ra mắt VTVcab ON – dịch vụ xem TRUYỀN HÌNH TRỰC TUYẾN đáng chú ý và nổi bật nhất hiện nay với hàng ngàn nội dung hấp dẫn:\n- Trực tiếp bóng đá, thể thao. Tổng hợp các giải đấu hàng đầu thế giới: Trực tiếp Ngoại Hạng Anh, La Liga, V.League, Bundesliga, Euro, Champions League, Cup Liên Đoàn Anh (độc quyền), Cúp Quốc gia Việt Nam (độc quyền), U23 Việt Nam, Vòng loại EURO, vòng loại World Cup; WTA Tennis - ATP tennis tour (độc quyền), … Cùng hàng trăm trận đấu hấp dẫn khác trên các nhóm kênh VTVcab ON, Hơn 200 kênh truyền hình phong phú, ấn tượng (VTV, VTC, SCTV, VTVcab, Box Movie, Today TV, Yeah 1, HTV, Dr.Fit, ANTV …)Website: http://vtvcab.vn/\nHotline: 1900 1515 (hỗ trợ online qua zalo, viber qua số điện thoại 0904678139)\nEmail: supportvod@vtvcab.vn",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/anh.png"
    },
    {
      "name": "K+ Android 7.0+",
      "versionNameNew": "12.3.100",
      "rated": "3",
      "categoty": "Truyền hình trực tuyến",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/K+/logo.png",
      "packageName": "com.irdeto.kplus",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/K+/K+TV_12.3.100.apk",
      "note": "Android 7 trở lên mới sử dụng được.\nNếu cài không được thì gỡ bản K+ trong máy ra rồi cài lại.\nỨng dụng K+ hoàn toàn mới sẽ mang tới cho người dùng trải nghiệm giải trí trọn vẹn với các kênh truyền hình trực tuyến, kho nội dung VOD độc quyền hấp dẫn, và đặc biệt là các gói thuê bao đa dạng tùy theo sở thích của khán giả yêu K+.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/K+/anh.jpg"
    },
    {
      "name": "VieON",
      "versionNameNew": "99.5.6",
      "rated": "3",
      "categoty": "Truyền hình trực tuyến",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VieON/VieON.png",
      "packageName": "com.vieon.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VieON/VieON-for-AndroidTV_99.5.6_mod_NoUpdate.apk",
      "note": "Mod không cập nhật : Xoá app đi trước rồi cài lại\nBạn sẽ không thể rời mắt khỏi VieON với hơn 60,000 giờ giải trí chất lượng cao và nội dung mới luôn được cập nhật hàng ngày:\n- Hơn 140 kênh truyền hình trực tuyến đặc sắc trong và ngoài nước như VTV, HTV, THVL, VTV6 HD, HTV3..., AXN, Cartoon Network, Fox Sport 3, CNN, BBC World News …\n- Phim độc quyền phát sóng cùng lúc với nước sản xuất.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VieON/anh.jpg,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VieON/anh1.jpg"
    },
    {
      "name": "TizenTube",
      "versionNameNew": "1.0.8",
      "rated": "5",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/TizenTube.png",
      "packageName": "io.gh.reisxd.tizentube.cobalt",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/TizenTube_v1.0.8.apk",
      "note": "Nếu cập nhật thất bại vui lòng gỡ ra trước và cài đặt lại !\nTizenTube Android 7, YouTube Leanback UI.\nAdblock, SponsorBlock, DeArrow.\nDisable shorts and more...",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh.webp,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh1.jpg"
    },
    {
      "name": "SmartYouTubeTV",
      "versionNameNew": "6.17.739",
      "categoty": "Giải trí",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/SYoutube.png",
      "packageName": "com.liskovsoft.videomanager",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/SYoutubeTV_6.17.739_mod_DLKey.apk",
      "note": "YoutubeTV Có thể đăng nhập.\nỨng dụng YoutubeTV miễn phí chặn quảng cáo xem video youtube trên Android TV Box.\nCác tính năng phát hành hiện tại:\nChạy trên Android 4.3 trở lên\nDuyệt qua Tin tức, Trò chơi, Âm nhạc\nDuyệt qua đăng ký, lịch sử, danh sách phát\nPhát video\nThích, Không thích hoặc Đăng ký cho video\nTìm kiếm video\nXem nội dung kênh đã đăng ký\nThay đổi các cài đặt khác nhau cho trình phát video\nXem trước hoạt ảnh cho video\nCác kênh Android TV và hỗ trợ tìm kiếm\"",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh.webp,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh1.jpg"
    },
    {
      "name": "NoTubeTV",
      "versionNameNew": "0.0.3DL",
      "rated": "4",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/logo_notube.png",
      "packageName": "com.ycngmn.notubetv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/NoTubeTV_v0.0.3DL.apk",
      "note": "Chạy được thiết bị cấu hình thấp Android 5.1.1 trở lên.\nYouTube Leanback UI.\nUnlocks 4K resolutions.\nAdblock, SponsorBlock, DeArrow.\nDisable shorts and more...",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh.webp,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh1.jpg"
    },
    {
      "name": "Youtube TV",
      "versionNameNew": "2.00.19",
      "categoty": "Giải trí",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/youtube_tv.png",
      "packageName": "com.google.android.youtube.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/YouTube_v2.00.19.apk",
      "note": "Ứng dụng YoutubeTV bản chính thức của google có quảng cáo cho Android TV 5,6 .\nCác tính năng phát hành hiện tại:\nChạy trên Android 5 trở lên\nDuyệt qua Tin tức, Trò chơi, Âm nhạc\nDuyệt qua đăng ký, lịch sử, danh sách phát\nPhát video\nThích, Không thích hoặc Đăng ký cho video\nTìm kiếm video\nXem nội dung kênh đã đăng ký\nThay đổi các cài đặt khác nhau cho trình phát video\nXem trước hoạt ảnh cho video\nCác kênh Android TV và hỗ trợ tìm kiếm\"",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh.webp,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Youtube/anh1.jpg"
    },
    {
      "name": "ToTube",
      "versionNameNew": "6.4-DL",
      "rated": "5",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeToStube/YoutubeToSmartNext.png",
      "packageName": "com.google.android.youtube.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeToStube/ToTube_v6.4-DL.apk",
      "note": "ToTube là cầu nối tìm kiếm kết quả giọng nói Youtube chuyển sang phát trên ứng dụng xem Youtube khác.\nĐể sử dụng được hãy xoá Youtube Gốc và cài đặt nó.\nFaceBook nhà phát triển: https://www.facebook.com/DinhlapD.Lp",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeToStube/ToTube.png"
    },
    {
      "name": "SmartTube Next(Stable)",
      "versionNameNew": "31.63",
      "rated": "5",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/SmartTube(Stable).png",
      "packageName": "com.teamsmart.videomanager.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/SmartTube_stable_31.63.apk",
      "note": "SmartTubeNext - Ứng dụng SmartYoutube miễn phí chặn quảng cáo xem video youtube trên Android TV Box.\nCác tính năng phát hành hiện tại:\nChạy trên Android 4.3 trở lên\nDuyệt qua Tin tức, Trò chơi, Âm nhạc\nDuyệt qua đăng ký, lịch sử, danh sách phát\nPhát video\nThích, Không thích hoặc Đăng ký cho video\nTìm kiếm video\nXem nội dung kênh đã đăng ký\nThay đổi các cài đặt khác nhau cho trình phát video\nXem trước hoạt ảnh cho video\nCác kênh Android TV và hỗ trợ tìm kiếm\"",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/anh.png"
    },
    {
      "name": "SmartTube Next(Stable)",
      "versionNameNew": "Luôn mới nhất",
      "rated": "5",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/SmartTube(Stable).png",
      "packageName": "com.teamsmart.videomanager.tv",
      "linkDownload": "https://github.com/yuliskov/SmartTubeNext/releases/download/latest/smarttube_stable.apk",
      "note": "SmartTubeNext - Ứng dụng SmartYoutube miễn phí chặn quảng cáo xem video youtube trên Android TV Box.\nCác tính năng phát hành hiện tại:\nChạy trên Android 4.3 trở lên\nDuyệt qua Tin tức, Trò chơi, Âm nhạc\nDuyệt qua đăng ký, lịch sử, danh sách phát\nPhát video\nThích, Không thích hoặc Đăng ký cho video\nTìm kiếm video\nXem nội dung kênh đã đăng ký\nThay đổi các cài đặt khác nhau cho trình phát video\nXem trước hoạt ảnh cho video\nCác kênh Android TV và hỗ trợ tìm kiếm\"",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/anh.png"
    },
    {
      "name": "SmartTube Next(Beta)",
      "versionNameNew": "Luôn mới nhất",
      "rated": "5",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/SmartTube(Beta).png",
      "packageName": "com.liskovsoft.smarttubetv.beta",
      "linkDownload": "https://github.com/yuliskov/SmartTubeNext/releases/download/latest/smarttube_beta.apk",
      "note": "SmartTubeNext - Ứng dụng miễn phí chặn quảng cáo xem video youtube trên Android TV Box.\nCác tính năng phát hành hiện tại:\nChạy trên Android 4.3 trở lên\nDuyệt qua Tin tức, Trò chơi, Âm nhạc\nDuyệt qua đăng ký, lịch sử, danh sách phát\nPhát video\nThích, Không thích hoặc Đăng ký cho video\nTìm kiếm video\nXem nội dung kênh đã đăng ký\nThay đổi các cài đặt khác nhau cho trình phát video\nXem trước hoạt ảnh cho video\nCác kênh Android TV và hỗ trợ tìm kiếm\"",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stube/anh.png"
    },
    {
      "name": "YouTube Kids TV",
      "versionNameNew": "1.12.02",
      "rated": "4",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeKids/Youtubetvkids.png",
      "packageName": "com.google.android.youtube.tvkids",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeKids/Youtubetvkids.apk",
      "note": "Trải nghiệm xem video trực tuyến an toàn hơn cho trẻ\nChúng tôi nỗ lực rất nhiều để giữ cho các video trên YouTube Kids luôn có nội dung phù hợp với gia đình. Để bảo vệ những người dùng nhỏ tuổi nhất trên mạng, chúng tôi kết hợp các bộ lọc tự động do nhiều nhóm kỹ sư thiết kế, quy trình xem xét thủ công và ý kiến phản hồi từ chính các bậc cha mẹ. Tuy nhiên, không có hệ thống nào là hoàn hảo và các video không phù hợp có thể vẫn lọt qua hệ thống của chúng tôi.\n- Nếu bị lỗi mạng(thử lại) thì hãy vào Cài đặt/Ứng dụng/Tìm phần quyền Internet và cấp cho youtube để sử dụng.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeKids/anh.jpg,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YoutubeKids/anh1.jpg"
    },
    {
      "name": "Nimo TV",
      "versionNameNew": "1.11.26",
      "rated": "2",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/NimoTV/logo.png",
      "packageName": "com.huya.nimo",
      "linkDownload": "https://d.apkpure.com/b/APK/com.huya.nimo?versionCode=14061&nc=arm64-v8a%2Carmeabi-v7a&sv=21",
      "note": "NiMO TV là một nền tảng livestream với mạng lưới phát sóng rộng khắp.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/NimoTV/anh.jpg"
    },
    {
      "name": "Bilibili TV",
      "versionNameNew": "1.7.1",
      "rated": "4",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BilibiliTV/logo.png",
      "packageName": "com.bstar.intl.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BilibiliTV/bilibili_modvip_v1.7.1.apk",
      "note": "Cộng đồng video Danmaku, hoạt hình giải trí hai chiều",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BilibiliTV/anh.jpg"
    },
    {
      "name": "Apple TV Android 8+",
      "versionNameNew": "13.5.0",
      "rated": "3",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/AppleTV/AppleTV.png",
      "packageName": "com.apple.atve.sony.appletv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/AppleTV/AppleTV_v13.5.0.apk",
      "note": "Yêu cầu android 8+\nỨng dụng Apple TV hiện có sẵn trên TV của bạn.\nThưởng thức Originals từ Apple TV+, thử các kênh cao cấp và mua hoặc thuê hàng nghìn bộ phim.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/AppleTV/anh.webp"
    },
    {
      "name": "Netflix mobile",
      "versionNameNew": "8.121.2 build 22 50727",
      "rated": "1",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Netflix/NetflixMobile.png",
      "packageName": "com.netflix.mediaclient",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Netflix/Netflix_8.121.2_build_22_50727.apk",
      "note": "Lưu ý là bản mobile cần dùng chuột\nTại Netflix, chúng tôi có những loạt phim, bộ phim, phim tài liệu và chương trình hài độc thoại đã giành nhiều giải thưởng. Chỉ cần có thiết bị di động là bạn sẽ có thể xem Netflix trong lúc di chuyển, đi làm hay nghỉ ngơi.\nNhững điều bạn sẽ yêu thích trên Netflix: Chúng tôi liên tục bổ sung phim và chương trình truyền hình mới. Hãy duyệt xem video mới hoặc tìm video mà bạn yêu thích và phát trực tuyến ngay trên thiết bị của bạn.\n• Bạn càng xem nhiều thì Netflix càng có thể đề xuất cho bạn những bộ phim và chương trình truyền hình mà bạn sẽ thích.\n• Bạn có thể tạo tới 5 hồ sơ trong một tài khoản. Hồ sơ giúp các thành viên trong gia đình của bạn tận hưởng Netflix theo sở thích cá nhân của họ.\n• Giúp trẻ tận hưởng Netflix một cách an toàn nhờ nội dung giải trí phù hợp với gia đình.\n• Tiết kiệm dữ liệu của bạn bằng cách tải video xuống thiết bị di động và xem ngoại tuyến ở bất kỳ đâu.Để xem chính sách quyền riêng tư, hãy vào https://signup.netflix.com/PrivacyPolicy.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Netflix/anh.png"
    },
    {
      "name": "Clip TV",
      "versionNameNew": "14.8",
      "rated": "3",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ClipTV/ClipTV.png",
      "packageName": "com.vgbm.clip.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ClipTV/ClipTV_AndroidTV_14.8_DL.apk",
      "note": "Xem Phim Free",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ClipTV/anh.jpg"
    },
    {
      "name": "iQIYI",
      "versionNameNew": "9.3.1",
      "rated": "3",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/iQIYI/logo.png",
      "packageName": "com.iqiyi.i18n.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/iQIYI/iQIYI_9.3.1.apk",
      "note": "iQIYI có kho video HD miễn phí, phụ đề tiếng Việt, nội dung hấp dẫn.\n\niQIYI có phụ đề tiếng Việt giúp bạn hiểu được nội dung video tốt hơn, trải nghiệm xem phim tốc độ cao chưa từng có, giao diện đơn giản rõ ràng. Trải nghiệm xem phim bản quyền độc quyền, chỉ ở iQIYI.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/iQIYI/anh.png"
    },
    {
      "name": "WeTV",
      "versionNameNew": "2.3.8.56481",
      "rated": "3",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeTV/WeTV.png",
      "packageName": "com.tencent.qqlivei18n",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeTV/WeTV_v2.3.8.56481.apk",
      "note": "Ứng dụng giải trí với kho phim ảnh, chương trình giải trí châu Á đặc sắc! WeTV đem đến những nội dung độc quyền dành cho bạn với trải nghiệm xem phim chất lượng.\nTính năng mới dành cho bạn:\nMục lục: Phim truyền hình, Phim lẻ và Chương trình giải trí được sắp xếp vào những trang khác nhau giúp bạn dễ dàng tìm kiếm nội dung theo sở thích.\nTiếp tục theo dõi tập phim bạn bỏ dở! Chúng tôi ghi nhớ thời điểm của tập phim và tiếp tục phát sóng cho bạn.\nChất lượng video: Chọn lựa chất lượng video theo nhu cầu của bạn! Từ 360P đến 1080P, bạn có thể tùy chỉnh chất lượng video phù hợp với dữ liệu di động hoặc đường truyền mạng của mình.\nPhụ đề: Thỏa sức thay đổi ngôn ngữ theo ý muốn với nhiều lựa chọn ngôn ngữ cho phụ đề.\nĐiều khiển màn hình: Thao tác ngón tay lên và xuống để chỉnh âm lượng và ánh sáng màn hình / Lướt ngón tay trái và phải để tua lại và tua nhanh video.\nInstagram: https://www.instagram.com/wetvvietnam/",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeTV/anh.png"
    },
    {
      "name": "Galaxy Play",
      "versionNameNew": "3.11.5",
      "rated": "4",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GalaxyPlay/GalaxyPlay.png",
      "packageName": "movies.fimplus.vn.andtv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GalaxyPlay/Galaxy_Play_v3.11.5.apk",
      "note": "Galaxy Play là Dịch vụ giải trí Online số 1 Việt Nam với thư viện phim bản quyền lớn nhất từ trước đến nay. Bạn sẽ luôn mãn nhãn khi hưởng đặc quyền thưởng thức sớm nhất tại Galaxy Play các phim Việt chiếu rạp có doanh thu đứng đầu mọi thời đại như “Cua Lại Vợ Bầu”, \"Mắt Biếc”, “Gái Già Lắm Chiêu”, \"Chị Trợ Lý Của Anh\"... Bên cạnh đó, hơn 5.000 phim Hollywood bom tấn và phim châu Á đặc sắc sẽ khiến bạn không thể rời khỏi màn hình đầy cuốn hút. Ngoài ra, Galaxy Play còn cung cấp hơn 8.000 giờ phim bộ tuyển chọn và 500 giờ phim thiếu nhi hấp dẫn đầy vui nhộn, giúp cả gia đình bạn có thời gian giải trí thoải mái nhất.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GalaxyPlay/anh.webp"
    },
    {
      "name": "Kodi 21.2-Omega",
      "versionNameNew": "21.2",
      "rated": "4",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kodi/logo.png",
      "packageName": "org.xbmc.kodi",
      "linkDownload": "https://mirrors.kodi.tv/releases/android/arm/kodi-21.2-Omega-armeabi-v7a.apk",
      "note": "Kodi là một trình phát phương tiện phần mềm mã nguồn mở và miễn phí từng đoạt giải thưởng và là trung tâm giải trí cho phương tiện truyền thông kỹ thuật số. Có sẵn dưới dạng ứng dụng gốc cho các hệ điều hành Android, Linux, BSD, macOS, iOS, tvOS và Windows , Kodi chạy trên hầu hết các kiến \u200B\u200Btrúc bộ xử lý phổ biến.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kodi/anh.webp"
    },
    {
      "name": "Kodi - PHAP",
      "versionNameNew": "22.0-ALPHA1",
      "rated": "4",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kodi/logo.png",
      "packageName": "org.xbmc.kodi",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kodi/KODI22-32Bit-PhapFerrari2025.apk",
      "note": "AE chỉ việc cài và sử dụng - dễ như ăn kẹo - Xem Phim Miễn phí - Xem Thể Thao Miễn Phí, Nhẹ mượt\n+ Tích hợp sẵn subscene\n+ Tua Phim như Youtube\n+ Tự động play phim bộ\n+ Chỉ cài 2 addon VNmedia và Elementum xem phim miễn phí\nHỗ trợ cho Android TV hoặc Box - Smartphone - Tablet \nAndroid là được nha \nChúc ae đầu tuần may mắn ⭐\nLink tải: nhập link vào web ( xoá khoảng trắng. )\nGg.Gg/phapapk - tìm app Kodi Premium \nĐường dẫn tải file KODI bản miễn phí :21.2 - Android - FREE\nĐường dẫn tải file KODI bản Fshare:21.2 - Android - FSHARE\nLưu ý: ae muốn đổi giao diện thành màu khác thì\nVào cài đặt - cài đặt giao diện - tiện ích bổ sung - tắt bật chủ đề, Để chỉnh màu sắc theo ý thích\nVào cài đặt - giao diện - màu sắc- ( chỉnh theo ý) Thanks bác Huỳnh Phước Pháp.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kodi/anh.webp"
    },
    {
      "name": "TikTok Lite",
      "versionNameNew": "41.4.4",
      "rated": "4",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TikTokLite/logo.png",
      "packageName": "com.zhiliaoapp.musically.go",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TikTokLite/TikTokLite_v41.4.4.apk",
      "note": "Lưu ý đây là bản Lite cho Mobile nên dùng phải dùng chuột để điều khiển\nTikTok Lite là phiên bản nhỏ hơn và nhanh hơn của TikTok, được thiết kế dành cho người dùng có RAM dưới 2GB, dữ liệu hạn chế hoặc kết nối với mạng 2G hoặc 3G.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TikTokLite/anh.png"
    },
    {
      "name": "CloudStream",
      "versionNameNew": "4.7.0",
      "rated": "5",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CloudStream/logo.png",
      "packageName": "com.lagradost.cloudstream3",
      "linkDownload": "https://github.com/recloudstream/cloudstream/releases/download/v4.7.0/4.7.0.apk",
      "note": "CloudStream là ứng dụng tiên tiến tích hợp nhiều dịch vụ phát trực tuyến vào một nền tảng gắn kết. Cho dù bạn là người mê phim, người xem phim truyền hình dài tập hay người đam mê âm nhạc, CloudStream đều đáp ứng mọi nhu cầu giải trí của bạn.\nNguồn Kho : rentry.org/cs3vn \n Nguồn tải luôn mới nhất https://github.com/recloudstream/cloudstream/releases",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/CloudStream/anh.jpg"
    },
    {
      "name": "Stremio",
      "versionNameNew": "1.6.7",
      "rated": "4",
      "categoty": "Phim truyện",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stremio/Stremio_logo.png",
      "packageName": "com.stremio.one",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stremio/Stremio_v1.6.7.apk",
      "note": "Stremio mang đến trải nghiệm giải trí an toàn, hiện đại và liền mạch. Với giao diện dễ sử dụng và thư viện nội dung đa dạng, bao gồm hỗ trợ 4K HDR, người dùng có thể thưởng thức các bộ phim và chương trình TV yêu thích trên tất cả các thiết bị của mình. Và với cam kết về bảo mật, Stremio là sự lựa chọn tối ưu để mang lại trải nghiệm phát trực tuyến chất lượng cao, an tâm.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Stremio/anh.png"
    },
    {
      "name": "Boba TV",
      "versionNameNew": "1.66.164",
      "rated": "3",
      "categoty": "Giải trí",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BobaTV/BoBaTV.png",
      "packageName": "com.vietigniter.boba",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BobaTV/BobaTV_v1.66.164.apk",
      "note": "Boba TV Ứng dụng xem phim HD online dành cho Android TV Box (Phiên bản nâng cấp của ứng dụng IMovies). Hỗ trợ xem phim HD, 3D ISO Bluray trên Android TV Box và Smart TV Android. Nếu bạn dùng cho điện thoại vui lòng tải ứng dụng Boba Phone để có trải nghiệm tốt hơn\n- Xem phim Full HD trên Android TV Box\n- Xem phim Bluray, ISO DTS trên Android Tv Box\n- Xem phim 3D ISO, 3D Bluray\n- Hỗ trợ điều khiển từ xa tivi bằng điện thoại thông qua ứng dụng Boba Phone",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/BobaTV/anh.jpg"
    },
    {
      "name": "Zing mp3",
      "versionNameNew": "23.09",
      "rated": "4",
      "categoty": "Âm nhạc",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ZingMP3/zing_mp3_tv.jpg",
      "packageName": "vng.zing.mp3",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ZingMP3/ZingMP3_v23.09mod.apk",
      "note": "Phiên bản Zing MP3 cho Android TV và Android Box\nZing MP3 là ứng dụng nghe nhạc miễn phí hàng đầu Việt Nam. Với kho nhạc chất lượng lớn từ http://mp3.zing.vn, bạn sẽ có trải nghiệm âm nhạc tuyệt vời nhất trên thiết bị di động của mình.\nTính năng nổi bật:\n- Giao diện được thiết kế vừa với màn hình TV",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ZingMP3/anh.png"
    },
    {
      "name": "Spotify",
      "versionNameNew": "1.76.1",
      "rated": "5",
      "categoty": "Âm nhạc",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Spotify/Spotify.png",
      "packageName": "com.spotify.tv.android",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Spotify/SpotifyADS.Removed.apk",
      "note": "Spotify cho Android TV là ứng dụng Spotify chính thức dành cho Android TV cho phép bạn thưởng thức tất cả âm nhạc có trong ứng dụng này bằng TV của bạn. Bạn có thể nghe hàng nghìn nghệ sĩ từ khắp nơi trên thế giới, thưởng thức danh sách phát được cá nhân hóa của mình và về cơ bản làm những điều tương tự như bạn sẽ làm bằng ứng dụng dành cho thiết bị di động hoặc máy tính để bàn của họ.\nSpotify cho Android TV là một ứng dụng thực sự thú vị cho bất kỳ ai sở hữu Android TV vì bạn có thể thưởng thức những bản nhạc hay nhất một cách thoải mái nhất. Tất cả những gì bạn phải làm là sử dụng điều khiển từ xa để phát danh sách phát yêu thích hoặc tăng hoặc giảm âm lượng.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Spotify/anh.jpg"
    },
    {
      "name": "MonPlayerTV",
      "versionNameNew": "2.0.0",
      "rated": "5",
      "categoty": "Thể thao",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MonPlayerTV/logo.png",
      "packageName": "org.monplayer.mpapp",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MonPlayerTV/MonPlayer_v2.0.0M.apk",
      "note": "Tích hợp sẵn Thập Cẩm TV và VeboTV\nMonPlayer là một trình phát video nâng cao. Nó định nghĩa lại trải nghiệm của bạn với một trình phát mạnh mẽ hỗ trợ nhiều định dạng.\nĐể sử dụng được hãy thêm nguồn vào nhé",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MonPlayerTV/anh1.jpg"
    },
    {
      "name": "ON Plus Smart TV",
      "versionNameNew": "1.1.72",
      "rated": "3",
      "categoty": "Thể thao",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/OnPlus.png",
      "packageName": "com.vtvcab.onsportstv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/ONPlus_v1.1.72.apk",
      "note": "ON Plus là ứng dụng số 1 Việt Nam về bóng đá, thể thao\n\nSỞ HỮU CÁC NGÔI SAO THỂ THAO TRONG LÒNG BÀN TAY\n\nBạn hâm mộ Messi, thích xem Lewandowski nhưng cũng không muốn bỏ lỡ các bàn thắng của Benzema? Với ON Plus, bạn có thể theo dõi đầy đủ những diễn biến trực tiếp của các sự kiện thể thao hấp dẫn nhất.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/anhONPlus.png,https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/VTVcabON/OnPlus.png"
    },
    {
      "name": "TV Bro",
      "versionNameNew": "1.8.4",
      "rated": "5",
      "categoty": "Trình duyệt web",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TVBro/tvBro.png",
      "packageName": "com.phlox.tvwebbrowser",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TVBro/tvbro1.8.4.apk",
      "note": "Trình duyệt web được tối ưu hóa để sử dụng với điều khiển từ xa của TV.Đặc trưng: làm việc với điều khiển TV hỗ trợ tab và dấu trang hỗ trợ tìm kiếm bằng giọng nói- chuyển đổi hỗ trợ tác nhân người dùng- sử dụng công cụ kết xuất web nội trang Android (dựa trên WebKit / Blink)- trình quản lý tải xuống tích hợp sẵn- lịch sử duyệt web- phím tắt Bây giờ nguồn mở:\nhttps://github.com/truefedex/tv-bro",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/TVBro/anh.webp"
    },
    {
      "name": "FireFox TV",
      "versionNameNew": "4.7.1.Phaptx5mod",
      "rated": "3",
      "categoty": "Trình duyệt web",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/FireFox/Firefox.png",
      "packageName": "org.mozilla.tv.firefox",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/FireFox/FireFoxTV.apk",
      "note": "Mô tả của Trình duyệt Firefox: riêng tư\nGiới thiệu phiên bản mới nhất của Firefox dành cho trình duyệt Android — Firefox Daylight. Phiên bản Firefox này được thiết kế lại với nhiều thay đổi để chạy nhanh hơn, dễ sử dụng, tùy chỉnh được và riêng tư. Trình duyệt Firefox có trình Bảo vệ Theo dõi Tăng cường bật mặc định để chặn hàng ngàn các phần mềm theo dõi quảng cáo và malware",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/FireFox/anh.png"
    },
    {
      "name": "Kiwi Browser - Fast & Quiet",
      "versionNameNew": "Luôn là bản mới nhất",
      "rated": "3",
      "categoty": "Trình duyệt web",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KiwiBrowser/logo.png",
      "packageName": "com.phlox.tvwebbrowser",
      "linkDownload": "https://d.cdnpure.com/b/APK/com.kiwibrowser.browser?version=latest",
      "note": "Kiwi Browser là một trình duyệt nhanh cho Android với một chặn pop-up mạnh mẽ, Trình duyệt Kiwi được tạo ra để duyệt internet, đọc tin tức, xem video và nghe nhạc mà không gây khó chịu.Duyệt trong hòa bình.Kiwi dựa trên Chromium",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KiwiBrowser/anh.png"
    },
    {
      "name": "Viettel Home",
      "versionNameNew": "1.4.0",
      "rated": "4",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ViettelHome/logo.png",
      "packageName": "com.vht.androidtv",
      "linkDownload": "https://github.com/DinhLap96/ListTivi/releases/download/AppTV/ViettelHome_v1.4.0.apk",
      "note": "Ứng dụng Viettel Home cho Android TV\n\nViettel Home là ứng dụng cung cấp giải pháp toàn diện về nhà thông minh và giám sát an ninh cho gia đình bạn.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ViettelHome/anh.png"
    },
    {
      "name": "Hik-Connect",
      "versionNameNew": "5.1.3.0320",
      "rated": "3",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Hik-Connect/HikConnect.png",
      "packageName": "com.hikvision.hikconnect",
      "linkDownload": "https://github.com/DinhLap96/ListTivi/releases/download/AppTV/Hik-Connect_5.1.3.0320.apk",
      "note": "Phải dùng chuột !\nỨng dụng Hik-Connect được thiết kế để hoạt động với các thiết bị của Hikvision như DVR, NVR, Camera.Tính năng chính:\n. Giám sát trong thời gian thực bằng điều khiển PTZ. Phát lại video. Hệ thống liên lạc âm thanh hai chiều. Thông báo cảnh báo tức thì bằng hình ảnh và video. Trả lời cuộc gọi từ chuông cửa/thiết bị liên lạc video. Bảng điều khiển an ninh im lặng từ xa. Chia sẻ thiết bị cho người khác với quyền hạn chế. Đăng nhập bằng vân tay thuận tiện và an toàn",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Hik-Connect/anh.jpg"
    },
    {
      "name": "Yoosee Mobile",
      "versionNameNew": "00.46.06.17",
      "rated": "3",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YooseeMobile/yoosee_logo.png",
      "packageName": "com.yoosee",
      "linkDownload": "https://github.com/DinhLap96/ListTivi/releases/download/AppTV/Yoosee_00.46.06.17.apk",
      "note": "Xem camera Yoosee -phải dùng chuột",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/YooseeMobile/anh.png"
    },
    {
      "name": "DMSS",
      "versionNameNew": "1.99.803",
      "rated": "3",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/DMSS/logo.png",
      "packageName": "com.mm.android.DMSS",
      "linkDownload": "https://github.com/DinhLap96/ListTivi/releases/download/AppTV/DMSS_v1.99.803.apk",
      "note": "Xem camera DMSS -phải dùng chuột\nỨng dụng DMSS có thể nâng cao hiệu quả quản lý bảo mật của bạn. Bạn có thể xem video giám sát theo thời gian thực và phát lại chúng mọi lúc, mọi nơi thông qua Wi-Fi hoặc mạng di động. Nếu cảnh báo thiết bị được kích hoạt, DMSS sẽ ngay lập tức gửi thông báo tức thời cho bạn.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/DMSS/anh.png"
    },
    {
      "name": "Imou Life",
      "versionNameNew": "8.3.0",
      "rated": "3",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouCamera/imou.png",
      "packageName": "com.mm.android.smartlifeiot",
      "linkDownload": "https://d.apkpure.com/b/APK/com.mm.android.smartlifeiot?versionCode=500340&nc=arm64-v8a%2Carmeabi-v7a&sv=21",
      "note": "Phải dùng chuột !\nImou là một ứng dụng bảo mật thông minh cho phép bạn chăm sóc ngôi nhà của mình.\n1. Tối ưu hóa quy trình thêm thiết bị.\n2. Chia sẻ thiết bị hiện hỗ trợ chọn quyền.\n3. Hỗ trợ hiển thị thông tin sản phẩm trên trang khởi động (đối với một số vùng).\n4. Cell Pro hiện hỗ trợ đặt lịch trình cánh tay.\n5. Hỗ trợ các chức năng liên quan cho Ranger IQ sắp ra mắt.\n6. Hỗ trợ chọn dịch vụ HUAWEI Push (dành cho điện thoại HUAWEI).\n7. Đã sửa các lỗi nhỏ khác.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouCamera/anh.jpg"
    },
    {
      "name": "Imou mod chuột",
      "versionNameNew": "1.2.90000",
      "rated": "3",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouCamera/imou.png",
      "packageName": "com.imoulife.hpo",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouCamera/ImouHPO_1.2.90000.apk",
      "note": "Mod dùng điều khiển bởi HPO !\nImou là một ứng dụng bảo mật thông minh cho phép bạn chăm sóc ngôi nhà của mình.\n1. Tối ưu hóa quy trình thêm thiết bị.\n2. Chia sẻ thiết bị hiện hỗ trợ chọn quyền.\n3. Hỗ trợ hiển thị thông tin sản phẩm trên trang khởi động (đối với một số vùng).\n4. Cell Pro hiện hỗ trợ đặt lịch trình cánh tay.\n5. Hỗ trợ các chức năng liên quan cho Ranger IQ sắp ra mắt.\n6. Hỗ trợ chọn dịch vụ HUAWEI Push (dành cho điện thoại HUAWEI).\n7. Đã sửa các lỗi nhỏ khác.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouCamera/anh.jpg"
    },
    {
      "name": "Imou Life HD",
      "versionNameNew": "1.1.10",
      "rated": "2",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouLifeHD/ImouLifeHD.png",
      "packageName": "com.imoulife.pad",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouLifeHD/ImouLifeHD(OnlyforPAD)_1.1.0Mod.apk",
      "note": "Giám sát ngôi nhà của bạn từ mọi nơi trên thế giới với ứng dụng Imou Life.\nGIỚI THIỆU CUỘC SỐNG IMOU\nỨng dụng Imou Life được tạo đặc biệt cho máy ảnh, chuông cửa, cảm biến, NVR và các sản phẩm IoT thông minh khác của Imou, cam kết tạo ra một cuộc sống an toàn, đơn giản và thông minh cho mọi người.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ImouLifeHD/anh.png"
    },
    {
      "name": "KBVIEW Plus",
      "versionNameNew": "4.0",
      "rated": "4",
      "categoty": "Camera",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KBVIEW/logo.png",
      "packageName": "com.mm.android.direct.KBVISIONVIEWPlus",
      "linkDownload": "https://d.apkpure.com/b/APK/com.mm.android.direct.KBVISIONVIEWPlus?versionCode=25&nc=arm64-v8a%2Carmeabi-v7a&sv=21",
      "note": "Ứng dụng giám sát camera cho thiết bị của KBVISION Tải xuống và cài đặt các phiên bản cũ của KBVIEW Plus phù hợp với kiểu máy của bạn và tận hưởng các tính năng yêu thích của bạn!",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/KBVIEW/anh.jpg"
    },
    {
      "name": "Zoom Mobile",
      "versionNameNew": "6.1.10.23840",
      "categoty": "Tiện ích",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Zoom/logo.png",
      "packageName": "us.zoom.videomeetings",
      "linkDownload": "https://cdn.zoom.us/prod/6.1.10.23840/zoom.apk",
      "note": "Zoom, ứng dụng cuộc họp, trò chuyện, học tập online.\nNếu cài cho TV cần dùng chuột và camera.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Zoom/anh.jpg"
    },
    {
      "name": "Kết nối Bluetooth",
      "versionNameNew": "1.0",
      "rated": "4",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Bluetooth/banner.png",
      "packageName": "com.example.bluetooth_connect",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Bluetooth/BluetoothConnected_v1.0.apk",
      "note": "Một số thiết bị trên Android TV (như Mi Box S hoặc Mi TV Q1e) không có tùy chọn \"Kết nối\" trong danh sách thiết bị Bluetooth. Do đó, đôi khi không thể kết nối tai nghe đã ghép nối. Bạn cần xóa chúng và ghép nối lại.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Bluetooth/anh1.png"
    },
    {
      "name": "Bluetooth Scanner",
      "versionNameNew": "2.0",
      "rated": "4",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Bluetooth/logo.jpg",
      "packageName": "com.zdworksinc.bluetoothtvscanner",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Bluetooth/BluetoothScannerATV_2.0.apk",
      "note": "Quét và ghép các thiết bị Bluetooth với TV Android của bạn.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Bluetooth/anh.jpg"
    },
    {
      "name": "ES File Explorer",
      "versionNameNew": "4.2.6.7",
      "categoty": "Tiện ích",
      "rated": "3",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ESFileExplorer/ES-File-Explorer.png",
      "packageName": "com.estrongs.android.pop",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ESFileExplorer/ESFileExplorerPro_4.2.6.7.apk",
      "note": "Trình quản lý tệp Android là trình quản lý tệp và ứng dụng mạng và cục bộ mạnh mẽ, miễn phí, Trình quản lý tệp, Trình quản lý mạng, Trình quản lý phương tiện. Người dùng trên toàn thế giới đã chọn trình quản lý tệp mạnh mẽ nhất!",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/ESFileExplorer/anh.png"
    },
    {
      "name": "Airscreen",
      "versionNameNew": "2.4.1",
      "categoty": "Tiện ích",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Airscreen/airscreen_banner.png",
      "packageName": "com.ionitech.airscreen",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Airscreen/AirScreen_2.4.1_Mod.apk",
      "note": "• Hoạt động với nhiều nền tảng khác nhau: Tận hưởng chia sẻ phương tiện mượt mà trên các thiết bị iOS 8-16, macOS 10.5-13, Android 5-12, ChromeOS 6-11 và Windows 7-11.\n• Hỗ trợ ứng dụng rộng rãi: Nghe các giai điệu từ iTunes, xem video trên YouTube, duyệt các trang web Safari và Chrome, v.v. Với hàng nghìn ứng dụng tương thích, AirScreen mang đến khả năng giải trí vô tận.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Airscreen/anh.jpg"
    },
    {
      "name": "Aptoide TV",
      "versionNameNew": "5.1.2",
      "categoty": "Tiện ích",
      "rated": "5",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/AptoideTV/aptoide_banner.png",
      "packageName": "cm.aptoidetv.pt",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/AptoideTV/AptoideTV_5.1.2.apk",
      "note": "Lưu ý : giọng nói đang hoạt động không được cập nhật Google.\nNếu lỗi do cập nhật Google: Hãy xoá Google TV từ DL Store và tiến hành cài lại.\nNếu lỗi giọng nói ,mà giao diện HomeTV mất logo ở giữa vậy là bản HomeTV bạn đang dùng là bản cố tình sử dụng từ bản bị các shop không uy tín chia sẻ với nhau.\nĐể hỗ trợ giọng nói lại hãy liên hệ tác giả qua thông tin ở phần Giới Thiệu ứng dụng.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/AptoideTV/anh.webp"
    },
    {
      "name": "MX Player Pro",
      "versionNameNew": "1.68.4",
      "rated": "5",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MXPlayer/MX_Player_Pro.png",
      "packageName": "com.mxtech.videoplayer.pro",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MXPlayer/MX_Player_Pro_1.68.4_Mod.apk",
      "note": "Trình duyệt phát video",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MXPlayer/anh.jpg"
    },
    {
      "name": "Mi Input",
      "versionNameNew": "1.0",
      "rated": "5",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MiInput/hdmi1.png",
      "packageName": "com.dinhlap.mitvinput",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MiInput/MitvInput.apk",
      "note": "Các cổng đầu vào HDMI",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/MiInput/hdmi1.png"
    },
    {
      "name": "Google TV",
      "versionNameNew": "2.2.0.138699360",
      "rated": "5",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GoogleTV/googleTV.png",
      "packageName": "com.google.android.katniss",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GoogleTV/GoogleV2.apk",
      "note": "Lưu ý : giọng nói đang hoạt động không được cập nhật Google.\nNếu lỗi do cập nhật Google: Hãy xoá Google TV từ DL Store và tiến hành cài lại.\nNếu lỗi giọng nói ,mà giao diện HomeTV mất logo ở giữa vậy là bản HomeTV bạn đang dùng là bản cố tình sử dụng từ bản bị các shop không uy tín chia sẻ với nhau.\nĐể hỗ trợ giọng nói lại hãy liên hệ tác giả qua thông tin ở phần Giới Thiệu ứng dụng.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GoogleTV/googleTV.png"
    },
    {
      "name": "Google Assistant",
      "rated": "5",
      "versionNameNew": "1.0",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GoogleTV/GoogleAssistant.png",
      "packageName": "com.dinhlap.google.assistant",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GoogleTV/GoogleAssistant_v1.0.apk",
      "note": "Chỉ là ứng dụng gọi ra giọng nói Google.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GoogleTV/GoogleAssistant.png"
    },
    {
      "name": "Super Voice",
      "versionNameNew": "2.6.3",
      "rated": "5",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SuperVoice/logoSV.png",
      "packageName": "com.linor.vn.supperVoice",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SuperVoice/SuperVoice_v2.6.3.apk",
      "note": "Super Voice cần bật ADB",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SuperVoice/anh.png"
    },
    {
      "name": "Map Voice",
      "versionNameNew": "2.2.0",
      "rated": "5",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SuperVoice/logoMV.jpg",
      "packageName": "com.linor.vn.mapVoice",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SuperVoice/MapVoice_v2.2.0.apk",
      "note": "Map Voice cần bật dịch vụ trợ năng",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/SuperVoice/anh2.png"
    },
    {
      "name": "Kiki - Trợ lý ảo Zalo",
      "versionNameNew": "24.01.01",
      "rated": "4",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kiki/kiki.png",
      "packageName": "ai.zalo.kiki.tv",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kiki/Kiki-AndroidTV_24.01.01.apk",
      "note": "Kiki - Android TV là phiên bản hỗ trợ Kiki sử dụng trên TV thông minh và các TV Box chạy hệ điều hành Android TV. Tính năng điều khiển bằng giọng nói mang lại sự tiện ích khi xem TV. Chỉ bằng một câu nói đơn giản, người dùng có thể giao tiếp với trợ lý Kiki để mở kênh truyền hình, video trên youtube và nhiều tác vụ hữu ích khác.\nPhát triển bởi : by Zalo Group",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Kiki/anh.webp"
    },
    {
      "name": "Downloader by AFTV",
      "versionNameNew": "1.4.4",
      "rated": "5",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/DownloaderByAFTV/Downloader.png",
      "packageName": "com.esaba.downloader",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/DownloaderByAFTV/DownloaderbyAFTV1.4.4.apk",
      "note": "Downloader by AFTV",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/DownloaderByAFTV/anh.jpg"
    },
    {
      "name": "Remote ADB",
      "versionNameNew": "8.0",
      "rated": "4",
      "categoty": "Tiện ích",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/RemoteADB/RemoteADB.png",
      "packageName": "com.dinhlap.adb",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/RemoteADB/RemoteADB_v8.0.apk",
      "note": "Từ bản 5.0 đổ xuống lên v6.0 hay gỡ ứng dụng ra trước rồi tải lại.\nThực hiện các lệnh adb trên Điện Thoại và TV.\n+ Cài đặt múi giờ.\n+ Xoá bộ nhớ đệm,.\n+Xoá dữ liệu,....",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/RemoteADB/RemoteADB.png"
    },
    {
      "name": "Weather Weawow°",
      "versionNameNew": "6.1.7",
      "rated": "5",
      "categoty": "Thời tiết",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeatherWeawow/Weawow.png",
      "packageName": "com.weawow",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeatherWeawow/Weawow_6.1.7.apk",
      "note": "Weawow là một ứng dụng thời tiết miễn phí (và không có quảng cáo) được cải tiến bởi những bức ảnh đẹp liên quan đến thời tiết do các nhiếp ảnh gia trên khắp thế giới chụp.\nCác bức ảnh thể hiện thời tiết hiện tại ở vị trí của bạn, cho bạn biết thời tiết đang tốt, nhiều mây, mưa hay tuyết để bạn có thể quyết định xem mình cần ô (dù) hay kính mát khi ra ngoài.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/WeatherWeawow/anh.png"
    },
    {
      "name": "Gboard TV",
      "versionNameNew": "12.8.11.514158943-tv_release-armeabi-v7a",
      "rated": "4",
      "categoty": "Bàn phím",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GboardKey/logo.png",
      "packageName": "com.google.android.inputmethod.latin",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GboardKey/GboardKey.apk",
      "note": "Nhập văn bản nhanh và thông minh kèm biểu tượng cảm xúc, ảnh GIF, v.v.\nGboard hội tụ tất cả tính năng mà bạn yêu thích ở Bàn phím Google – tốc độ và độ tin cậy, phương thức Nhập bằng cách lướt, nhập liệu bằng giọng nói, Chữ viết tay và nhiều tính năng khác",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/GboardKey/anh.png"
    },
    {
      "name": "Browser",
      "versionNameNew": "2.0.5",
      "rated": "4",
      "categoty": "Trình duyệt web",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Browser/logo.png",
      "packageName": "com.internet.tvbrowser",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Browser/Browser_2.0.5.apk",
      "note": "Trình duyệt của chúng tôi là trình duyệt web Internet dành cho Android TV. Bạn có thể mở các trang web và lướt Internet. Trình duyệt của chúng tôi được tối ưu hóa để điều khiển TV. Tất cả các chức năng của trình duyệt web có thể được sử dụng dễ dàng bằng điều khiển từ xa của TV.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Browser/anh.png"
    },
    {
      "name": "Televizo - IPTV player",
      "versionNameNew": "1.9.3.21",
      "categoty": "Truyền hình trực tuyến",
      "rated": "4",
      "logo": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Televizo/logo.png",
      "packageName": "com.ottplay.ottplay",
      "linkDownload": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Televizo/Televizo_v1.9.3.21.apk",
      "note": "Xem các kênh truyền hình trực tiếp chất lượng cao với Televizo - trình phát IPTV mọi lúc mọi nơi.\nXem trực tiếp các kênh truyền hình HD ngay trên thiết bị di động của bạn. Cho dù bạn thích tin tức, thể thao, phim ảnh hay giải trí, Televizo - trình phát IPTV mang đến trải nghiệm xem mượt mà mọi lúc mọi nơi.",
      "preview": "https://raw.githubusercontent.com/ADCBFE/aef/refs/heads/main/Televizo/anh.png"
    }
  ]
}